# Generated by Django 5.2.17 on 2026-09-30 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با09 شروع شده و 11 رقم باشد.', regex='^09/d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
